INCLUDES = ../include/ircd.h ../include/ircsprintf.h ../include/md5.h \
	../include/modulos.h ../include/protocolos.h ../include/parseconf.h \
	../include/struct.h
MODULEFLAGS=-fPIC -DPIC -shared
modulo: $(FUENTE).c
	@if [ ! -r include ] ; then \
		ln -s ../include include; \
	fi
	$(CC) $(CFLAGS) $(MODULEFLAGS) -DENLACE_DINAMICO -o $(FUENTE).so $(FUENTE).c 
