#!/bin/sh

PID_FILE="./colossus.pid"
PID_BACKUP="./colossus.pid.bak"
if [ "$1" = "start" ] ; then
	echo "Iniciando Colossus"
	if [ -r $PID_FILE ] ; then
		mv -f $PID_FILE $PID_BACKUP
	fi
	./colossus
	sleep 1
	if [ ! -r $PID_FILE ] ; then
		echo "Se ha detectado un error en la ejecución de Colossus"	
		echo "====================================================="
		echo "Comprueba todos los errores primero "
		echo "====================================================="
		tail -n 5 ./colossus.log
		if [ -r $PID_BACKUP ] ; then
			mv -f $PID_BACKUP $PID_FILE
		fi
	fi
elif [ "$1" = "stop" ] ; then
	echo "Deteniendo Colossus"
	kill -9 `cat $PID_FILE`
elif [ "$1" = "rehash" ] ; then
	echo "Refrescando Colossus"
	kill -1 `cat $PID_FILE`
elif [ "$1" = "restart" ] ; then
	echo "Reiniciando Colossus"
	kill -2 `cat $PID_FILE`
else
	echo "Uso: ./servicios start|stop|rehash|restart"
fi
