#undef BSD_RELIABLE_SIGNALS
#define DEFAULT_PERMISSIONS _S_IWRITE
#define FCNTLH
#undef FORCE_CORE
#define GETTIMEOFDAY
#undef INET6
#define LISTEN_SIZE 5
#define MAXCONNECTIONS 1024
#undef NBLOCK_BSD
#undef NBLOCK_POSIX
#undef NBLOCK_SYSV
#define NEED_ABS
#define NEED_BZERO
#undef NEED_INET_NTOA
#define NEED_STRCASECMP
#undef NEED_STRERROR
#define NEED_STRNCASECMP
#undef POSIX_SIGNALS
#undef STATIC_LINKING
#define STDLIBH
#define STRINGH
#undef SYSV_UNRELIABLE_SIGNALS
#undef UNDERSCORE
#define UNISTDH
