TvServ {
	funciones {
		
		/*
		 * Muestra la programación de las televisiones autonómicas y nacionales de España.
		 * Nivel por defecto: 1.
		 * Comando por defecto: TV.
		 */
		tv;
		
		/*
		 * Muestra el horóscopo del día.
		 * Nivel por defecto: 1.
		 * Comando por defecto: HOROSCOPO.
		 */
		horoscopo;
		
		/*
		 * Muestra la previsión meteorológica del día de cualquier pueblo del mundo.
		 * Nivel por defecto: 1.
		 * Comando por defecto: TIEMPO.
		 */
		tiempo;
		
		/*
		 * Muestra la cartelera de los cines españoles. Hora, cines, aforo, pases, películas, de un cine en particular de una ciudad.
		 * Nivel por defecto: 1.
		 * Comando por defecto: CINE.
		 */
		cine;
		
		/*
		 * Muestra información técnica, sinopsis y datos de interés de una película que se esté proyectando en algún cine de España.
		 * Nivel por defecto: 1.
		 * Comando por defecto: PELIS.
		 */
		pelis;
		
		/*
		 * Muestra la clasificación de la Liga Nacional de Fútbol de España. 1a y 2a división.
		 * Nivel por defecto: 1.
		 * Comando por defecto: LIGA.
		 */
		liga;
		
		/*
		 * Muestra la ayuda.
		 * Nivel por defecto: 1.
		 * Comando por defecto: HELP
		 */
		help;
	};
};

/*
 * Recuerde que puede utilizar los bloques funcion {} o alias { } para personalizar estos comandos.
 *
 * www.redyc.com
 */
 