NewsServ {
	funciones {
		
		/*
		 * Da de alta a un usuario o canal en este servicio.
		 * Nivel por defecto: 1.
		 * Comando por defecto: ALTA.
		 */
		alta;
		
		/*
		 * Da de baja a un usuario o canal en este servicio.
		 * Nivel por defecto: 1.
		 * Comando por defecto: BAJA.
		 */
		baja;
		
		/*
		 * Muestra la ayuda.
		 * Nivel por defecto: 1.
		 * Comando por defecto: HELP.
		 */
		help;
	};
};

/*
 * Recuerde que puede utilizar los bloques funcion {} o alias { } para personalizar estos comandos.
 *
 * www.redyc.com
 */
 